<<<<<<< HEAD

org.slf4j.simpleLogger.defaultLogLevel=warn


=======
org.slf4j.simpleLogger.defaultLogLevel=warn

>>>>>>> 7cf81797c4116cfe5161e66038702007c50642c2
org.slf4j.simpleLogger.log.com.zaxxer.hikari=warn